package com.huateng.ebank.entity.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huateng.ebank.entity.orm.Dic;
import com.huateng.ebank.entity.orm.User;

import com.huateng.ebank.entity.dao.DicDao;
import com.huateng.ebank.entity.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dicDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DicDao dicDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dicDaoConfig = daoConfigMap.get(DicDao.class).clone();
        dicDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dicDao = new DicDao(dicDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Dic.class, dicDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        dicDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DicDao getDicDao() {
        return dicDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
